### PR TITLE
Sim

### PR DESCRIPTION
**Pull request by Student007**
as @rwaldron suggested I've created an test compatible extension of TesselSimulator.

### CODE REVIEW

**Comment by rwaldron** [comment]
@Student007 looks like this has some previous commits in it's history—can you do a rebase on this branch?

```
# assuming you have a remote called "upstream" that points to "git@github.com:tessel/t2-cli.git"...
git pull --rebase upstream master
```

Ping either @johnnyman727 or me for review. I'm on vacation at the moment, so I might not have a chance to do the review—but I will try!!

**Comment by Student007** [comment]
@rwaldron I am unsure:
Is this done by selecting the branch `sim` and run `git pull --rebase upstream master`

**Comment by Student007** [comment]
... does it need more after that or is Git magic and will sync github brunch sim and this pull request automatically ? :smile:

**Comment by Student007** [comment]
bad idea
> Too many errors. (51% scanned).

**Comment by Student007** [comment]
`grunt test` I did :cry:

**Comment by Student007** [comment]
should be clean now :facepunch:

**Comment by johnnyman727** [comment]
@Student007 are you sure you rebased on master? If you look at the commits above, you'll notice that you still have a commit from me included here.

**Comment by Student007** [comment]
@johnnyman727 yes I did copy paste from Slack chat ... I AM SURE...

**Comment by Student007** [comment]
... and when I wrote last comment ... :facepunch:  ... it was clean and mergable

**Comment by johnnyman727** [comment]
Closing in favor of https://github.com/tessel/t2-cli/pull/297 which will merge cleanly.

**Pull request closed without merging**
