### PR TITLE
Preemptive update for next node-usb release

### PR DESCRIPTION
**Pull request by johnnyman727**

### CODE REVIEW

**Comment by rwaldron** [comment]
In the future, version bumping should be it's own commit that is not tied to a PR.

**Comment by johnnyman727** [comment]
@rwaldron I'm fine with that but why should it not be in a PR?

**Comment by rwaldron** [comment]
Sorry, I didn't mean "no PR at all", I meant "not tied to a PR for something else"—sorry that was definitely not clear in my first message.

**Comment by johnnyman727** [comment]
Gotcha! Yeah, that seems totally reasonable.

**Pull request merged**
