### PR TITLE
Add lan and usb flags for run and push 

### PR DESCRIPTION
**Pull request by Frijol**
r? @johnnyman727 or @HarleyKwyn

### CODE REVIEW

**Comment by HarleyKwyn** [comment]
This looks kosher to me, but I don't have a tessel 2 to test it with.

**Comment by johnnyman727** [comment]
When you try to use an option that isn't available (like trying to deploy over LAN when the Tessel is not connected to the internet) it just prints out that no Tessels were found:
```
➜  t2-cli git:(kb-run) t2 run test/test-deploy-script.js --lan
INFO Connecting to Tessel...
ERR! No Tessels Found
```

Do we want to have a more descriptive error message for this case? The [issue](https://github.com/tessel/t2-cli/issues/79) doesn't actually document what should happen.

**Comment by Frijol** [comment]
That's what I thought it should do– reads to me as "no tessels found on LAN". What would you prefer?

**Comment by HarleyKwyn** [comment]
FWIW I think that this is a correct response. The suggestion Kelsey just
specified would also be good.

**Comment by johnnyman727** [comment]
Fair enough - looks good!

**Comment by HarleyKwyn** [comment]
Could quickly be added with
```
        var connectionType = '';
        if(opts.lan) connectionType = 'LAN';
        if(opts.usb) connectionType = 'USB';
        reject('No ' + connectionType + ' Tessels Found');
```
on line 98 I beleive.

**Comment by Frijol** [comment]
I personally like it as is

**Comment by HarleyKwyn** [comment]
:+1:

**Pull request merged**
