### PR TITLE
lib: fixed exit codes

### LINKED ISSUE #174: t2 list exits with status 1 even on success

### PR DESCRIPTION
**Pull request by LinusU**
*fixes #174*

A number of places exited with a faulty code when really nothing went wrong. This should fix that.

I'm a tiny bit uncertain on the two in `lib/tessel/deploy.js`, would be cool if someone could review :sunglasses:

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM, but @johnnyman727 should have a look.

Someone should do a follow up commit with tests that use spies to check the exit codes.

**Comment by johnnyman727** [comment]
This looks good to me as well. @LinusU do you want to write the unit tests (see /test/unit/ for examples) as @rwaldron points out or do you want me to write them?

**Comment by johnnyman727** [comment]
Also, just as a note on process, we've usually been having at least one other team member sign off and then the original PR author merges, so merge when you feel comfortable.

**Comment by LinusU** [comment]
I can write them, should that be a separate pull request? In that case I'll merge this one now.

**Comment by rwaldron** [comment]
@LinusU ideally in the same PR (this one)

**Comment by rwaldron** [comment]
@LinusU ping me in [#reviews](https://tessel.slack.com/messages/reviews/details/) when ready

**Comment by LinusU** [comment]
@rwaldron Sorry, I've been a bit busy this week. Thank you for fixing the tests :+1:

**Pull request merged**
