### PR TITLE
toggle wifi-iface instead of wifi-device

### LINKED ISSUE #487: Turning off wifi disables wireless radio
At the moment, [`commands.turnOnWifi()`](https://github.com/tessel/t2-cli/blob/master/lib/tessel/commands.js#L55-L57) disables the `wifi-idevice` `radio0` instead of the 'wifi' `wifi-iface`. This should be changed so that the `lan` access point `wifi-iface` can continue running when wifi is turned off.

### PR DESCRIPTION
**Pull request by HipsterBrown**
Fixes #487

### CODE REVIEW

**Comment by johnnyman727** [comment]
@hipsterbrown, this is great. Could you add one or more unit tests that confirms that this command is called correctly?

**Comment by HipsterBrown** [comment]
@johnnyman727 Sure. Making sure it's called? Or that it's calling the right `uci` setting?

**Comment by johnnyman727** [comment]
Mostly the latter

**Comment by HipsterBrown** [comment]
Got it. I'll work on it.

**Comment by HipsterBrown** [comment]
@johnnyman727 Tests added. :)

**Comment by johnnyman727** [comment]
Perfect!

**Pull request merged**
