### PR TITLE
Added windows installation instructions

### PR DESCRIPTION
**Pull request by dalestone**
@rwaldron  Added installation instructions for windows users. I didn't know whether to leave the error message out? Let me know if you think it would be better without.

Thanks

### CODE REVIEW

**Comment by Frijol** [comment]
Thanks for doing this! I'll let someone with a windows computer try this out before merging but I'm really excited that you wrote this.

**Comment by rwaldron** [comment]
@Frijol I asked @dalestone to contribute these changes since they solved his installation issue [here](https://github.com/tessel/t2-cli/issues/196) . The issue itself isn't Tessel specific and the fix is recommended by the npm team; should we wait for another confirmation or is that adequate? Either is fine with me

**Comment by dalestone** [comment]
@Frijol @rwaldron  No problem happy to help! I am going to take a look at the t2-vm next as I've hit a few issues with trying to run that on Windows.

**Comment by Frijol** [comment]
Okay, that seems pretty well tested then! Merging.

**Comment by rwaldron** [comment]
@dalestone @Frijol thanks!

**Pull request merged**
