### PR TITLE
General Cleanup (Order: 1)

### LINKED ISSUE #104: General CLI code refactoring and cleanup
- [x] Move all functionality to Promises
- [ ] Close the connection after each use
- [ ] Standardize logging style
- [ ] Fix error handling in `tessel-2.bin`
- [ ] General cleanup

### PR DESCRIPTION
**Pull request by johnnyman727**
Goal: fix #104.

This PR will also add some better debugging capabilities for `t2 list`. You'll just need to type `DEBUG=discovery:* t2 list` or `DEBUG=discovery:lan t2 list` or `DEBUG=discovery:usb t2 list`.

### CODE REVIEW

**Comment by rwaldron** [comment]
@johnnyman727 can you clean up these lint nits: https://travis-ci.org/tessel/t2-cli/builds/71706371 Thanks!!

**Comment by johnnyman727** [comment]
@rwaldron yep! I didn't get around to cleaning it up yet.

**Comment by johnnyman727** [comment]
@rwaldron any idea why the tests are hitting this error?
```
Testing lan_connection.js........F
>> LAN.Scanner.prototype.start - updateDiscoveredThrows
>> Error: 'Cannot read property \'fullname\' of undefined' == 'get outta here!'
>> at null.<anonymous> (test/unit/lan_connection.js:160:12)
>> at emit (events.js:107:17)
>> at /Users/Jon/Work/technical/t2-cli/lib/lan_connection.js:166:16
>> at process._tickCallback (node.js:355:11)
```

I couldn't understand how it's supposed to work.

**Comment by rwaldron** [comment]
@johnnyman727 I think this needs to be broken up into different PRs—it's really hard to grok these changes altogether like this.

**Comment by rwaldron** [comment]
The broken test was ensuring that scanner errors could be caught with an error handler: https://github.com/tessel/t2-cli/commit/2230b8eb483e66a0a0068fd748d1625fce9032c3#diff-a9a705c264927afb490d6ba8a1d038faR100

**Comment by rwaldron** [comment]
The issue is caused by https://github.com/tessel/t2-cli/pull/215/files#diff-e49c18af28b7866f1c40c82d8451cffbR155 because the test sends no arguments when the `update` event is emitted: https://github.com/tessel/t2-cli/blob/master/test/unit/lan_connection.js#L157 so the wrong error is thrown, because `data` is undefined and therefore has no `fullname` property.

**Comment by johnnyman727** [comment]
Fixed, thanks @rwaldron!

**Comment by johnnyman727** [comment]
Ready for review.

**Comment by rwaldron** [comment]
- Ran unit tests locally
- Smoke test: 

```
rwaldron at nova in ~/clonez/t2-cli on jon-general-cleanup
$ t2 list
INFO Searching for nearby Tessels...
  arnold  USB
rwaldron at nova in ~/clonez/t2-cli on jon-general-cleanup
$ t2 rename johnconnor
INFO Connecting to Tessel...
INFO Connected to arnold over LAN
INFO Changed name of device arnold to johnconnor
rwaldron at nova in ~/clonez/t2-cli on jon-general-cleanup
$ t2 rename arnold
INFO Connecting to Tessel...
INFO Connected to johnconnor over LAN
INFO Changed name of device johnconnor to arnold
rwaldron at nova in ~/clonez/t2-cli on jon-general-cleanup
$ cd resources/
rwaldron at nova in ~/clonez/t2-cli/resources on jon-general-cleanup
$ t2 run index.js
INFO Connecting to Tessel...
INFO Connected to arnold over LAN
INFO Writing index.js to RAM on arnold (60956.16 kB)...
INFO Deployed.
INFO Running index.js...
^C
```

LGTM.

**Pull request merged**
