### PR TITLE
Refactors the way we open and close Tessel connections

### LINKED ISSUE #335: Aborting Script Deployed over USB Causes USB Daemon Crash
After connect to my Tessel over USB, run blinky and control+c out of it:
```
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
^CINFO Stopping script...
Unhandled rejection TypeError: Cannot read property 'connectionType' of undefined
    at closeThem (/Users/Jon/Work/technical/t2-cli/lib/controller.js:186:32)
    at /Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:187:20
    at /Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:239:13
    at /Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:119:13
    at _arrayEach (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:91:13)
    at _forEachOf (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:118:9)
    at _each (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:83:13)
    at Object.async.forEachOf.async.eachOf (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:215:22)
    at /Users/Jon/Work/technical/t2-cli/lib/controller.js:184:11
    at tryCatcher (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:70:37)
    at Object.controller.closeTesselConnections (/Users/Jon/Work/technical/t2-cli/lib/controller.js:183:10)
    at /Users/Jon/Work/technical/t2-cli/lib/controller.js:384:29
    at runMicrotasksCallback (node.js:337:7)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error code 9 upon remote process exit for command: node /tmp/remote-script/index.js
    at USBProcess.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_process.js:58:26)
    at USBProcess.g (events.js:199:16)
    at USBProcess.emit (events.js:107:17)
    at Parser.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_daemon.js:117:14)
    at Parser.emit (events.js:107:17)
    at Parser._write (/Users/Jon/Work/technical/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at ondata (_stream_readable.js:540:20)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at InEndpoint.emit (events.js:107:17)
    at Transfer.transferDone (/Users/Jon/Work/technical/t2-cli/node_modules/usb/usb.js:295:9)
➜  t2-demo  DEBUG=discovery,discovery:*,controller t2 list
INFO Searching for nearby Tessels...
  discovery:usb Device found with matching PID and VID +0ms
  discovery:usb Opening device! +3ms
  discovery Connection opened: +24ms undefined of type USB
  discovery Fetching name: +0ms CP5H379VQGVMPGNG0702A18HFX
  discovery:usb Writing USB command: +8ms [ 'uci', 'get', 'system.@system[0].hostname' ]
  discovery:lan Device found: +243ms Harold._tessel._tcp.local
  discovery:lan Device ready: +2s Harold.local
  discovery Connection opened: +2ms Harold.local of type LAN
  discovery Fetching name: +0ms Harold.local
  discovery:lan Writing LAN command: +1ms [ 'uci', 'get', 'system.@system[0].hostname' ]
	Harold	LAN
  discovery Timeout hit! Waiting for pending to finish... +2s
  discovery Done! Stopping. +2ms
```

The first unhandled rejection error is unrelated (I believe) and fixed with #332. 

However, we then see that the process exited with error code 9 (SIGKILL). Just after this happens, the USB Daemon on T2 dies (at least, I can no longer see it running with `ps`) and the call to fetch the name of the device in the subsequent `t2 list` call never returns so only the `LAN` connection is displayed.

That means you can no longer use the USB connection until Tessel is restarted. 

Probably related to #324.

### PR DESCRIPTION
**Pull request by johnnyman727**
Fixes #335 and #324.

TODO:
* [x] Get `t2 update` to finish properly
* [x] Any Grunt style warnings
* [x] Fix broken tests
* [x] Add new tests

### CODE REVIEW

**Comment by johnnyman727** [comment]
@rwaldron could you review? Essentially, this PR does two things:

1. Refactors `controller.js` such that we have a standard way of fetching a Tessel, executing some command, then closing that Tessel connection when we're done. That way, when we make new CLI commands, we just have to worry about the functionality specific to that command and not how we fetch Tessels or whether or not they've been closed.
2. Cleans up the Node process completion. Before this PR, there were two different ways a process could be closed: by completing properly and exiting back out through callbacks into `tessel-2.js` or by sending a SIGINT that was captured in `tessel.js` and then forcible `process.exit`ed after closing connections. This PR changes that so that with either a SIGINT or the completion of a command, the CLI will always close connections and exit through `tessel-2.js`.

**Comment by johnnyman727** [comment]
Or @Frijol if you have time.

**Comment by Frijol** [comment]
Excited for this! But got this issue:

```sh
➜  tesselcode  t2 run index.js
INFO Looking for your Tessel...
INFO Connected to Frank over USB
INFO Writing index.js to RAM on Frank (8123.392 kB)...
^C^C
➜  tesselcode  t2 list
INFO Searching for nearby Tessels...
WARN No Tessels Found
```

I had to ctrl+c twice to get out of the script, and then no tessels were found in t2 list

**Comment by Frijol** [comment]
Other than that, tried ctrl+c to exit a script and pulled out power to exit a script, and t2 cli was able to find it again after – so the main point of this PR is working

**Comment by johnnyman727** [comment]
@Frijol nice find.

I was able to reproduce this issue on both this branch and on master so I don't believe it was introduced here. I will go ahead and create a separate issue for it.

**Comment by Frijol** [comment]
lgtm then

**Comment by johnnyman727** [comment]
@Frijol the issue you found has been reported [here](https://github.com/tessel/t2-cli/issues/345).

**Comment by rwaldron** [comment]
```
rwaldron at nova in ~/robotz/tessel-pir
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop over LAN
INFO Writing index.js to RAM on bishop (5.12 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/index.js
1443391275444 1
1443391275512 1
1443391275524 1
1443391275541 1
1443391275552 1
1443391275560 1
1443391275586 1
1443391275611 1
1443391275623 1
1443391275631 1
1443391275639 1
1443391275646 1
1443391275652 1
1443391275660 1
1443391275667 1
1443391275674 1
1443391275682 1
1443391275690 1
1443391275697 1
1443391275705 1
1443391275711 1
1443391275723 1
1443391275729 1
1443391275736 1
1443391275744 1
^C1443391276619 1
INFO Stopping script...
rwaldron at nova in ~/robotz/tessel-pir
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop over LAN
INFO Writing index.js to RAM on bishop (5.12 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/index.js
1443391578601 1
1443391578680 1
1443391578690 1
1443391578699 1
1443391578721 1
1443391578727 1
1443391578754 1
1443391578766 1
1443391578775 1
1443391578781 1
1443391578788 1
1443391578796 1
1443391578803 1
1443391578811 1
1443391578818 1
1443391578825 1
1443391578832 1
^Crwaldron at nova in ~/robotz/tessel-pir
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop over LAN
INFO Writing index.js to RAM on bishop (5.12 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/index.js
1443391590314 1
1443391590382 1
1443391590394 1
1443391590411 1
1443391590423 1
1443391590431 1
1443391590456 1
1443391590481 1
1443391590493 1
1443391590502 1
1443391590510 1
1443391590517 1
1443391590524 1
1443391590531 1
1443391590538 1
1443391590545 1
^Crwaldron at nova in ~/robotz/tessel-pir
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop over LAN
INFO Writing index.js to RAM on bishop (5.12 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/index.js
1443391601785 1
1443391601854 1
1443391601865 1
1443391601927 1
1443391601938 1
1443391601946 1
1443391601951 1
1443391601957 1
1443391601963 1
1443391601970 1
1443391601978 1
1443391601985 1
1443391601993 1
1443391602000 1
1443391602006 1
1443391602012 1
1443391602020 1
1443391602027 1
1443391602034 1
1443391602041 1
1443391602050 1
1443391602056 1
1443391602063 1
^Crwaldron at nova in ~/robotz/tessel-pir
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop over LAN
INFO Writing index.js to RAM on bishop (5.12 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/index.js
1443391613358 1
1443391613426 1
1443391613437 1
1443391613455 1
1443391613508 1
1443391613519 1
1443391613526 1
1443391613531 1
1443391613536 1
1443391613542 1
1443391613549 1
1443391613556 1
1443391613564 1
^Crwaldron at nova in ~/robotz/tessel-pir
```

All grunt tasks pass.

**Comment by rwaldron** [comment]
LGTM, land when ready.

**Pull request merged**
