### PR TITLE
t2 provision

### PR DESCRIPTION
**Pull request by Frijol**
Fixes for https://github.com/tessel/t2-cli/issues/64
Can be merged, or I'll keep working through the checklist.

### CODE REVIEW

**Comment by Frijol** [comment]
@johnnyman727 I had to manually merge your edits from https://github.com/tessel/t2-cli/pull/100, can you take a look and make sure it still works properly?

**Comment by johnnyman727** [comment]
Works now!

**Comment by nplus11** [comment]
`var setup = require('./tessel/provision');`
lol @setup

**Comment by johnnyman727** [comment]
looks ready!

**Pull request merged**
