### PR TITLE
reboots tessel after restore

### LINKED ISSUE #964: t2 restore should automatically reboot tessel
There was an [issue](https://github.com/tessel/t2-cli/issues/493#issuecomment-219169290) rebooting the tessel during the implementation of `t2 restore` command. 

Area of interest:  `REQ_PWR_RST` [command](https://github.com/tessel/t2-firmware/blob/master/firmware/usb.c#L362-L365) 

Could use [sys_reset](https://github.com/tessel/t2-firmware/blob/master/common/hw.h#L270-L272) instead

### PR DESCRIPTION
**Pull request by dbuentello**
fixes #964

### CODE REVIEW

**Comment by dbuentello** [comment]
This fails testing. I think it has to do with test setup...
```
Testing restore.jsERR! Detected CLI crash TypeError: Cannot read property 'controlTransfer' of undefined
ERR!     at exportables.enableWrite.then.then.then.then.then (/Users/dbuentello/_repos/Github/dbuentello/t2-cli/lib/tessel/restore.js:255:19)
ERR!     at process._tickCallback (internal/process/next_tick.js:103:7) TypeError: Cannot read property 'controlTransfer' of undefined
ERR!     at exportables.enableWrite.then.then.then.then.then (/Users/dbuentello/_repos/Github/dbuentello/t2-cli/lib/tessel/restore.js:255:19)
ERR!     at process._tickCallback (internal/process/next_tick.js:103:7)
```

Should I rewrite test or move code somewhere else?

**Comment by rwaldron** [comment]
No, please do not rewrite/remove any tests. I will make a PR to your branch that adds a mock and a simple test to the existing tests. Once you merge it, you'll be able to pass the tests and then add more tests (based on the example I set forth)

**Comment by rwaldron** [comment]
Ready for you to merge: https://github.com/dbuentello/t2-cli/pull/1

**Comment by rwaldron** [comment]
Nice! That was fast. Ok, so I left you a comment in this section: https://github.com/tessel/t2-cli/pull/983/files#diff-10458d609c4258a1a5a558303f4b58c1R448 which should give you an idea of what needs to be tested. Please let me know if you need _any_ further guidance there—I'm here to help :)

**Pull request merged**
