### PR TITLE
Minor fix: removes "node" or "iojs" befor "t2 command" in help msg

### PR DESCRIPTION
**Pull request by Student007**

### CODE REVIEW

**Comment by Student007** [comment]
@ 10:32:00  http://time.is/GMT ... All checks have passed and the branch is up-to-date with the base branch !

**Comment by rwaldron** [comment]
Nice! That was always kind of weird to see :)

**Comment by johnnyman727** [comment]
:clap: Thanks, @Student007!

**Comment by Student007** [comment]
:white_check_mark: yes this was weird :ghost: --- I am surprised I got the point at first I was experimenting with the code itself. At this point I noticed I was trying .script() at the wrong place. :relaxed:

**Pull request merged**
