### PR TITLE
Revised "overlooked asset" detection; tesselinclude hinting. Fixes gh-644

### PR DESCRIPTION
**Pull request by rwaldron**
This revision fixes some annoyances and garbage that I overlooked in the first implementation: 

1. This revised warning is _never_ shown for --full, because that makes no sense, all files will be pushed every time. 
2. Takes into consideration that asset files and directories might indeed be directly required by the program. 
3. Doesn't display such an awful message, no more file list, etc. 
4. Puts the information in the --help text (both run and push)

Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by rwaldron** [comment]
cc @johnnyman727 @HipsterBrown

**Comment by johnnyman727** [comment]
r+

**Comment by HipsterBrown** [comment]
Very smart system. Nice that we can scan the dependency graph like that. Great update. :+1:

**Comment by rwaldron** [comment]
Thanks everyone

**Pull request merged**
