### PR TITLE
Upgrade to newer version of mDNS-js

### PR DESCRIPTION
**Pull request by LinusU**
Related: #854

### CODE REVIEW

**Comment by Frijol** [comment]
Any concern about https://github.com/mdns-js/node-mdns-js/commit/ee17f8b2723198c239cf08f480b79c5799b276dd ?

**Comment by Frijol** [comment]
also, since that appears to be the only commit in that release, LGTM

**Comment by LinusU** [comment]
I don't know, to be honest that project doesn't look that solid at all, there are a lot of open issues and pull requests that haven't been attended to...

As you say, the only added commit is the one that changes the package.json so this shouldn't really change anything code related, but it might be worth looking into other libs for more stability, e.g. [bonjour](https://www.npmjs.com/package/bonjour) which I have used before :)

**Comment by LinusU** [comment]
Funnily enough there was a 0.4.1 that wouldn't have printed the warning, but that never got published to npm ð

**Comment by LinusU** [comment]
I think it would be a good idea to smoke test this before merging though, just to be sure... I'm not with my tessel currently but could probably test it in a few days unless someone else beats me too it. Sounds good?

**Comment by Frijol** [comment]
no problem, we just released CLI yesterday so this is not urgent

**Comment by rwaldron** [comment]
I rebased this! Woohoo!

**Comment by HipsterBrown** [comment]
I'll smoke test this tonight and merge if it works.

**Comment by LinusU** [comment]
Thank you guys, sorry for dropping the ball on this ❤️

**Comment by rwaldron** [comment]
@HipsterBrown I've been using this branch since yesterday, no issues.

**Pull request merged**
