### PR TITLE
Add an advisory in package.json/engines that Node needs to be version 4

### PR DESCRIPTION
**Pull request by cflewis**
Add a warning that you need to be using Node 4 LTS

### CODE REVIEW

**Comment by LinusU** [comment]
I've been using Node 6 with t2-cli, why wouldn't it work? Was there something breaking in 6.2.0?

**Comment by johnnyman727** [comment]
@LinusU I'm really curious how you compiled the `usb` module with Node 6!

**Comment by johnnyman727** [comment]
I think a fix that might be more maintainable is by updating the [`engines` field of the package.json](https://docs.npmjs.com/files/package.json). That way, `npm` will automatically print out a warning when the CLI is installed with an incompatible version of Node and we won't have to explicitly remember to update the README when we make the CLI Node 6.x compatible (because we'll get a reminder every time a person installs).

**Comment by LinusU** [comment]
Hmmm, maybe I'm dreaming and I actually used nvm...

I think that the engines field would be nice 👍

**Comment by johnnyman727** [comment]
LGTM!

**Pull request merged**
