### PR TITLE
wifi connection status tests

### PR DESCRIPTION
**Pull request by HipsterBrown**
Most likely to be merged after #471

### CODE REVIEW

**Comment by rwaldron** [comment]
I think `kb-wifi` branch needs to be rebased first?

**Comment by johnnyman727** [comment]
Yeah, I believe the first two commits are already in master.

**Comment by HipsterBrown** [comment]
@rwaldron you're right. I knew I was missing something. Will be done asap.

**Comment by HipsterBrown** [comment]
I think I set this branch up incorrectly. I branched `kb-wifi`, then rebased #471 into it rather than branching #471 and rebasing `kb-wifi` into it. Might be why there are conflicts. ¯\_(ツ)_/¯

**Comment by rwaldron** [comment]
Let me see if I can fix it

**Comment by rwaldron** [comment]
I can't figure it out. 

@HipsterBrown I hate to do this to you, but let's land @Frijol's patch and go from there

**Comment by HipsterBrown** [comment]
That's fine. I can probably pick out the changes from this branch to make an update with tests in another PR.

**Comment by HipsterBrown** [comment]
This is done in #471 now.

**Pull request closed without merging**
