### PR TITLE
Use os.homedir() to resolve the user's home directory

### PR DESCRIPTION
**Pull request by tikurahul**
Fixes https://github.com/tessel/t2-cli/issues/750

### CODE REVIEW

**Comment by LinusU** [comment]
LGTM

**Comment by rwaldron** [comment]
Sorry, but I was just in the middle of reviewing this as well. There are other places where this might apply.  Also, there are no tests :\

**Comment by rwaldron** [comment]
Follow up commit: https://github.com/tessel/t2-cli/commit/9d88920b3ede02d81c886724205cec4408d9cec4

**Comment by tikurahul** [comment]
My apologies. I just saw this. ❎

**Pull request merged**
