### PR TITLE
lib: remove workaround for mdns library bug

### PR DESCRIPTION
**Pull request by LinusU**
This workaround is no longer required since this have been fixed upstream in `0.4.0`

@johnnyman727 care to review?

### CODE REVIEW

**Comment by rwaldron** [comment]
@LinusU can you take a look at the travis-ci failures? You can run these all locally:

```
npm install # one time set up
```

Then run: 

```
grunt
```

**Comment by rwaldron** [comment]
Probably just need to swap these around: 

- https://github.com/tessel/t2-cli/blob/master/test/unit/lan_connection.js#L108-L115
- https://github.com/tessel/t2-cli/blob/master/test/unit/lan_connection.js#L155-L164

**Comment by LinusU** [comment]
Yes, that's probably it, thanks! I should have run the tests before I committed, don't know why I didn't... I'll fix this :)

**Comment by johnnyman727** [comment]
@LinusU I made it very easy: https://github.com/LinusU/t2-cli/pull/1 :)

**Comment by johnnyman727** [comment]
Thanks @LinusU!

**Pull request merged**
