### PR TITLE
Whitelist aws sdk json

### PR DESCRIPTION
**Pull request by rwaldron**
cc @HipsterBrown or @johnnyman727

### CODE REVIEW

**Comment by HipsterBrown** [comment]
LGTM. Nice update to the tests as well. 👍 

Do we have any documentation about submitting new whitelisted files? May be something nice to add in a FAQ / troubleshooting section of the docs.

**Comment by rwaldron** [comment]
> Do we have any documentation about submitting new whitelisted files? May be something nice to add in a FAQ / troubleshooting section of the docs.

Not yet, can you write something up?

**Comment by HipsterBrown** [comment]
Sure thing. 😄

**Comment by rwaldron** [comment]
@HipsterBrown you're the best

**Pull request merged**
