### PR TITLE
Fix restart script arguments bug.

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by rwaldron** [comment]
@HipsterBrown Can you review this?

**Comment by HipsterBrown** [comment]
# Smoke Test

## Project

**Setup:**
`mkdir tessel-test`
`cd tessel-test`
`t2 init`

Run project with `t2 run index.js`

## Results:

```bash
Nicks-MacBook-Pro:tessel-test hipsterbrown$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to tessel-router.
INFO Building project.
INFO Writing project to RAM on tessel-router (3.072 kB)...
INFO Deployed.
INFO Running index.js...
I'm blinking! (Press CTRL + C to stop)
```

Successfully ran script!

**Comment by rwaldron** [comment]
Can you do a `t2 restart`?

**Comment by HipsterBrown** [comment]
Yup. It worked.

**Comment by rwaldron** [comment]
Thanks!

**Pull request merged**
