### PR TITLE
cleanup and simplify cli commands

### PR DESCRIPTION
**Pull request by wprater**
- add callControllerCallback to consolidate callback and success/fail
  thenables into a callback function
- add callControllerWith to consolidate callback and success/fail thenables

### CODE REVIEW

**Comment by wprater** [comment]
@johnnyman727 some quick simplification and cleanup.. if you like, lmk..

**Comment by johnnyman727** [comment]
@wprater I do like! Once you make `grunt` happy, feel free to merge.

**Comment by wprater** [comment]
want me to delete these merged branches?

**Comment by johnnyman727** [comment]
Yeah, let's keep the repo clean

**Pull request merged**
