### PR TITLE
Make a link for users to join Slack

### PR DESCRIPTION
**Pull request by johnnyman727**

### CODE REVIEW

**Comment by tcr** [comment]
Should we mention what Slack is?

"Join us on Slack, a team communication platform."

Or something less corporate.

**Comment by Frijol** [comment]
I kinda like it as is– "join the conversation" feels appropriate

**Comment by johnnyman727** [comment]
I added a little note about what it is. Does this work for you @tcr and @Frijol?

**Comment by Frijol** [comment]
:/ I like this less because it conveys no new information. If we need to specify, why not "the project's chat" or similar

**Comment by johnnyman727** [comment]
@Frijol  How about `Join us on Slack, the project's chat client!`

**Comment by Frijol** [comment]
sure

**Pull request merged**
