### PR TITLE
Add custom hostname flag to uci when using `t2 rename`

### LINKED ISSUE #252: t2 update: Sometimes the hostname changes after update
We need to figure out why the hostname changes sometimes after update. Once we know why, we can take steps to set it back to what it was previously.

### PR DESCRIPTION
**Pull request by wyze**
This is the other half of the puzzle for https://github.com/tessel/openwrt-tessel/pull/59 and completes https://github.com/tessel/openwrt-tessel/issues/19.

Also would close #252 and make https://github.com/tessel/t2-start/pull/117 not necessary.

### CODE REVIEW

**Comment by johnnyman727** [comment]
@wyze so glad you're working on this.

Just so I'm sure I understand your proposed solution - you're basically creating a new flag that notes whether the name has been rewritten and then checking for that flag during the update process?

Have you confirmed that the flag is not overwritten during an update? I think it probably would not be overwritten since other `uci` configs are not overwritten but I just wanted to check.

What do you think we should do about the `t2 rename --reset` command? Should we remove this new flag or set it to zero? I personally don't see a need to do that because I think the only case a user might expect a new name is if they ran `t2 update -n` to completely erase all configs.

I might suggest that we name the new flag `custom_hostname_set` because it sounds more like a flag to me.

We may want to consider just writing to a flag whenever a new hostname is made. Like I said, the only case where we want to change the hostname is on `t2 update -n` which would delete that flag anyway (so a new name would be set).

**Comment by wyze** [comment]
# Smoke Test

---

#### Rename

```
❯ t2 rename Tester
INFO Looking for your Tessel...
INFO Connected to Tessel-02A30510B2C5.
INFO Changed name of device Tessel-02A30510B2C5 to Tester
```

#### Make sure flag is set

```
❯ t2 root
INFO Looking for your Tessel...
INFO Connected to Tester.
INFO Starting SSH Session on Tessel. Type 'exit' at the prompt to end.


BusyBox v1.23.2 (2016-05-10 21:55:24 EDT) built-in shell (ash)

Tessel 2  /  Built on OpenWrt
root@Tester:~# cat /etc/config/system

config system
	option timezone 'UTC'
	option hostname 'Tester'
	option custom_hostname '1'
```

#### Update

```
❯ t2 update --openwrt-path openwrt-ramips-mt7620-tessel-squashfs-sysupgrade-node-4.4.3.bin
INFO Looking for your Tessel...
INFO Connected to Tester.
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 19.14 MB. This will take 2-4 minutes...
INFO Transfer complete.
INFO Starting OpenWRT update.
INFO Please do not remove power from Tessel.
INFO This process will take at least two minutes...
INFO Configuration is saved during update.
WARN No firmware binary loaded... skipping firmware update
INFO Finished updating Tessel with local builds.
```

#### List

```
❯ t2 list
INFO Searching for nearby Tessels...
	USB	Tester
```

#### `t2 update -n`

```
❯ t2 update --openwrt-path openwrt-ramips-mt7620-tessel-squashfs-sysupgrade-node-4.4.3.bin -n
INFO Looking for your Tessel...
INFO Connected to Tester.
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 19.14 MB. This will take 2-4 minutes...
INFO Transfer complete.
INFO Starting OpenWRT update.
INFO Please do not remove power from Tessel.
INFO This process will take at least two minutes...
INFO Configuration is not saved during update.
WARN No firmware binary loaded... skipping firmware update
INFO Finished updating Tessel with local builds.
```

#### List

```
❯ t2 list
INFO Searching for nearby Tessels...
	USB	Tessel-02A30510B2C5
```

**Comment by wyze** [comment]
> Just so I'm sure I understand your proposed solution - you're basically creating a new flag that notes whether the name has been rewritten and then checking for that flag during the update process?

The CLI will set the flag, and then the uci defaults file, [50-tessel-hostname](https://github.com/tessel/openwrt-tessel/blob/custom-hostname-flag/files/etc/uci-defaults/50-tessel-hostname) performs the check during the update on whether or not to change the hostname.

> Have you confirmed that the flag is not overwritten during an update? I think it probably would not be overwritten since other uci configs are not overwritten but I just wanted to check.

See the smoke test above. 😄  

> What do you think we should do about the `t2 rename --reset` command? Should we remove this new flag or set it to zero? I personally don't see a need to do that because I think the only case a user might expect a new name is if they ran `t2 update -n` to completely erase all configs.

The `t2 rename --reset` command still uses the underlying `setName` function which sets this flag, so even on reset the flag would still be set. My smoke test above confirms that passing `-n` to `t2 update` does reset the hostname.

> I might suggest that we name the new flag custom_hostname_set because it sounds more like a flag to me.

Works for me, I'll get that changed tomorrow.

> We may want to consider just writing to a flag whenever a new hostname is made. Like I said, the only case where we want to change the hostname is on `t2 update -n` which would delete that flag anyway (so a new name would be set).

I think it might already do this, because `t2 rename <newname>` and `t2 rename --reset` use the same `setName` function which sets the flag. I am not aware of any other way that a new hostname is made. Unless you mean by when the `50-tessel-hostname` file gets executed, and it updates the hostname, set the flag there too?

**Comment by johnnyman727** [comment]
> See the smoke test above. 😄

:+1: 

> Unless you mean by when the 50-tessel-hostname file gets executed, and it updates the hostname, set the flag there too?

Yes, this is exactly what I mean. This would solve the one sort of corner case where someone updates their Tessel, never changes the default name but becomes accustomed to it (or writes some code to access THEIR_TESSEL.local or whatever) and then is surprised to find the name updated and code broken after an update. This would just be an OpenWRT patch and not a CLI patch.

**Comment by wyze** [comment]
Okay. I will add that to the `uci-default` file in the PR over there: https://github.com/tessel/openwrt-tessel/pull/59

**Comment by wyze** [comment]
@johnnyman727, Is this good to go? I merged https://github.com/tessel/openwrt-tessel/pull/59 since more smoke tests were successful.

**Comment by johnnyman727** [comment]
@wyze we don't need this anymore, right? OpenWRT will set its own custom_hostname field as soon as it's updated without a `-n` flag.

**Comment by wyze** [comment]
Ah, you might be right. Let me double check.

**Comment by wyze** [comment]
Yes, this is no longer needed.

**Pull request closed without merging**
