### PR TITLE
Enables pushed app before starting

### LINKED ISSUE #707: [push] Starting app from Flash does not work occasionally
Cross posted from [the Forums](https://forums.tessel.io/t/tessel-2-does-not-start-my-application-with-push/2329/26)

To Reproduce (On Windows 8/10):
```
t2 init
t2 push index.js
```
Expected Results: Blinking LEDs

Actual Results: No Change in LED state

### PR DESCRIPTION
**Pull request by johnnyman727**
Fixes #707.

Travis will likely have issues with unrelated tests until #754 is merged.

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@johnnyman727 How can I smoke test this update? Should I follow the steps [here](https://github.com/tessel/t2-cli/issues/707#issue-151008830)?

Do you know why some of the `controller.js` tests are failing?

**Comment by johnnyman727** [comment]
@HipsterBrown that would be a good smoke test if you have a windows machine. Otherwise, I would just make sure `t2 run` and `t2 push` work as expected with `t2 init`-generated assets.

The `controller.js` tests are failing because of the `t2 update --list` tests. Somehow our SSL certs on the build server became invalidated (maybe out of date?) so the `http.get`s are failing. I made mocks for the `requestBuildList` function in #292 to get that build working on Travis but it might have been better form to break the fix out into a separate PR. :/ Anyway, once that PR lands, this PR should be green too.

**Comment by HipsterBrown** [comment]
Ok thanks. I'll give that a shot when I get home tonight. 

It looks like #292 is nearly ready to be merged but if it still needs some time, it might be worth breaking out those mocks into a separate PR still so we can get this fix merged as well. That's up to you though.

**Comment by johnnyman727** [comment]
@HipsterBrown Okay, you'e sufficiently persuaded me to stop being lazy. I broke the unit test fix out into #754.

**Comment by rwaldron** [comment]
As a matter of principle, this shouldn't land until the tests are green—we're all agreed on that, right?

**Comment by rwaldron** [comment]
I've just given appveyor a kick to re-run those tests.

**Comment by johnnyman727** [comment]
@rwaldron how do you force AppVeyer to re-run the tests?

**Comment by HipsterBrown** [comment]
All green tests means LGTM! 👍

**Comment by rwaldron** [comment]
There's a "re-build" button :)

**Pull request merged**
