### PR TITLE
Update to use simplified t2-firmware LED API

### PR DESCRIPTION
**Pull request by rwaldron**
More details here: https://github.com/tessel/t2-firmware/pull/105

### CODE REVIEW

**Comment by johnnyman727** [comment]
Tried it and it worked last night! @rwaldron maybe we should hold off on merging this until I get a chance to put out a new release? (sometime this week)

**Comment by rwaldron** [comment]
No problem!

**Comment by rwaldron** [comment]
Ping @johnnyman727

**Comment by johnnyman727** [comment]
@rwaldron I haven't forgotten about this! Will try to get a release out this week.

**Comment by Frijol** [comment]
superseded by https://github.com/tessel/t2-cli/pull/398
tried to PR your PR @rwaldron to add my one line change but got lost in git for more than 10 minutes so calling that a loss..

**Pull request closed without merging**
