### PR TITLE
Restore relpath to script entrypoint. Fixes gh-266

### PR DESCRIPTION
**Pull request by rwaldron**
@sidwarkd can you review this please? Thanks!

### CODE REVIEW

**Comment by rwaldron** [comment]
@johnnyman727 ping

**Comment by johnnyman727** [comment]
looks good to me

**Comment by sidwarkd** [comment]
Sorry @rwaldron. Missed this in the flood of emails. Looks good and thanks for taking care of it.

**Comment by rwaldron** [comment]
Cool, thanks everyone!

**Pull request merged**
