### PR TITLE
Setup ~/.tessel at install time. Fixes gh-796

### PR DESCRIPTION
**Pull request by rwaldron**
- Reorganize postinstall operations
- Consolidate into "installer.js"
- Tests for all postinstall operations

## Smoke Test

1. Run: `rm -rf ~/.tessel/`
  - IMPORTANT: This will wipe out all of your preferences re: provisioning, last run program, crash reporter and all of your locally cached pre-compiled binary modules. You can alternatively make a copy of your present `~/.tessel` before rm'ing. 
2. Elsewhere, create a new project: 
  ```
  mkdir t2-800 && cd t2-800 && t2 init
  ```
2. Back in your local t2-cli repo: 
  - pull the branch
  - Run: `npm install`
3. Navigate to `~/.tessel/`, which should now exist and contain a `preferences.json` file
4. Next, run `cd .. & rm -rf .tessel` (again)
5. Navigate to your `t2-800` directory:
  - Run: `t2 run index.js`, which should result in an error.
6. Navigate back in your local t2-cli repo: 
  - Run: `npm install`
7. Navigate _back_ to your `t2-800` directory:
  - Run: `t2 run index.js`, which should be successful this time.

Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by rwaldron** [comment]
@johnnyman727 or @HipsterBrown

**Comment by HipsterBrown** [comment]
Code looks good to me. I'll smoke test tonight.

**Comment by rwaldron** [comment]
@HipsterBrown I'm working on adding a few more tests, but smoke test when ready

@carlbaron ping, can you review and do the smoke test? Thanks!

**Comment by rwaldron** [comment]
Ok, done with adding tests

**Comment by carlbaron** [comment]
@rwaldron Smoke test isn't working for me. After steps 1-3 I don't have a `.tessel` in my home directory.

**Comment by HipsterBrown** [comment]
Went through the smoke test and everything worked as expected. :+1:

**Comment by HipsterBrown** [comment]
@carlbaron Can you comment with your current OS and versions of Node.js & `npm`?

**Comment by carlbaron** [comment]
OS X: 10.10.5
Node: 4.4.7
npm: 2.15.8

**Comment by rwaldron** [comment]
@carlbaron 

> After steps 1-3 I don't have a .tessel in my home directory.

Did you pull _this_ branch?

**Comment by rwaldron** [comment]
I just upgraded from Node 4.4.5 to Node. 4.4.7 and walked through the smoke test again, everything worked as expected.

**Comment by rwaldron** [comment]
Rebased

**Comment by carlbaron** [comment]
@rwaldron Well that's embarrassing. Yeah I pulled `master`, my only excuse is it was a long day and I was tired. I'll try it on the correct branch

**Comment by rwaldron** [comment]
Ah! No worries—everyone has long days that result in silly mistakes :) Totally forgivable. Thanks for doing a follow up walk through!!

**Pull request merged**
