### PR TITLE
Only detatch usb listeners if we have a usb controller

### LINKED ISSUE #397: If a machine doesn't have `usb` support, an error will be thrown upon process completion
```
➜  ~  t2 list
ERR! WARNING: No usb controller found on this system.
INFO Searching for nearby Tessels...
^C/Users/Jon/Work/technical/t2-cli/lib/usb_connection.js:339
  usb.removeAllListeners('attach');
     ^
TypeError: Cannot read property 'removeAllListeners' of undefined
    at USB.Scanner.stop (/Users/Jon/Work/technical/t2-cli/lib/usb_connection.js:339:6)
    at TesselSeeker.stop (/Users/Jon/Work/technical/t2-cli/lib/discover.js:126:18)
    at process.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/controller.js:108:16)
    at process.g (events.js:199:16)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

### PR DESCRIPTION
**Pull request by johnnyman727**
Fixes #397.

### CODE REVIEW

**Comment by Frijol** [comment]
`t2 list` still fails:

```sh
➜  ~  node --version
v4.2.1
➜  ~  t2 list
ERR! WARNING: No usb controller found on this system.
INFO Searching for nearby Tessels...
Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 223.
[1]    25438 abort      t2 list
```

**Comment by johnnyman727** [comment]
Hmm I think this error might be unrelated to this change.

**Comment by Frijol** [comment]
anything in particular you'd like me to test?

**Comment by johnnyman727** [comment]
I'm not sure how to test it w/o getting weird errors like that. The case I ran into was when I manually compiled [the `node-usb` module with a fix for Node v4.x.x](https://github.com/nonolith/node-usb/pull/91), tried to run the CLI with Node v0.12, and ran `t2 list`. 

Since all the tests pass, this is such a small change, and getting the test condition might take a while, it would be great if you could just double check that the code change looks okay. If you run `t2 list` with this branch and it doesn't break, I'll be satisfied.

**Comment by Frijol** [comment]
did that, seems fine

**Comment by johnnyman727** [comment]
Good enough for me!

**Pull request merged**
