### PR TITLE
controller.menu cleaned up

### PR DESCRIPTION
**Pull request by Student007**
### API
method | return | info
-----|------|-----
| controller.menu.create(tessels, opts, title) | promise | calls `make`and `show` before returning the selected single `Tessel` object to the next promise. In the case `EXIT` is selected, the `process.exit()` will be executed due to the reason there is not reason to work with nothing. **The params `opts` and `title` are optional !** while `opts` in fact is useless at the moment but `title` will become useful to create an information line above the options to select (e.g. `*You stupid customer forgot to use the awesome command line param TESSEL=WhatTheHellYouCallYourPoorTessel*`).
| controller.menu.make(tessels, rtm, title) | promise | Of cause you may use `make` if you own a `rtm` object. The returned promise will contain the reference to the made menu what is to use with `show` to become useful. 
| controller.menu.show(rtm) | promise | Of cause you may use only that to show a menu. The promises resolve will pipe the index like this: `controller.menu.make(tessels, rtm, title).then(controller.menu.show(rtm)).then(function(index) {resolve(tessels[index]);});` 
| controller.menu.clear() | promise | it simple clears the terminal and resolves the returned promise

### Usage
```
controller.menu.create(tessels)
.then(function(tessel) {
// do something with the selected Tessel
});

```

### CODE REVIEW

**Comment by rwaldron** [comment]
This is a great PR message :)

**Comment by Student007** [comment]
:blush: thanks

**Comment by johnnyman727** [comment]
@Student007 This is great! I opened a PR on your branch to integrate this service into `Tessel.get`: https://github.com/Student007/t2-cli/pull/2. Note that I changed some of the output to be more consistent with the rest of the CLI (ie removed IP addresses).

Remaining items to finish:
* [ ] Merge my PR into your PR
* [ ] Fix existing tests. Currently, running `grunt` (the test runner) will pop up the menu. We need a way for it to run w/o using the menu.
* [ ] Create new unit tests. I'm not sure the best way to do this for this kind of PR that requires interactivity. I suppose it should be as easy as writing to `process.stdin` but I haven't tried it yet. @rwaldron do you have any suggestions here?

**Comment by Student007** [comment]
@johnnyman727 I will write unit tests as easy as writing API test but without chaining the hole used case. Testing `terminal-menu` itself would be a pull to the project `terminal-menu`
About fixing other tests, I will add a testing flag. I remember about asking for this and didn't got an answer so I removed the last solution for testing interactive mode.
**Is there a best practice about identifying test mode ?**

**Comment by Student007** [comment]
@rwaldron Is there a best practice about identifying test mode ?

**Comment by Student007** [comment]
@rwaldron [I got it](https://github.com/rwaldron/nino-io/blob/master/Gruntfile.js)

**Comment by rwaldron** [comment]
> Create new unit tests. I'm not sure the best way to do this for this kind of PR that requires interactivity. I suppose it should be as easy as writing to process.stdin but I haven't tried it yet. @rwaldron do you have any suggestions here?

We don't need to test the menu itself, that's for the author of that module to do. We just need to test that the functions it calls do the right thing for both good and bad inputs.

**Comment by rwaldron** [comment]
@Student007 that's correct, and it's already available in t2-cli: https://github.com/tessel/t2-cli/blob/master/test/common/bootstrap.js also, it's not necessary to change any of the actual cli code, just stub the menu's API in the tests

**Comment by rwaldron** [comment]
FFS. terminal-menu doesn't export the actual Menu class, which means you can't EVER stub the methods. More importantly: **we absolutely do not want conditional code interwoven throughout the actual cli code.**

**Comment by rwaldron** [comment]
After you merge @johnnyman727's PR, please also merge this: https://github.com/Student007/t2-cli/pull/3

Don't worry about new tests for now, it's not clear how/if it will even be possible. We can follow up later.

**Comment by Student007** [comment]
@rwaldron does it mean I shell stop writing tests for `controller.menu` at all ?
To fix the problem `Tessel.get` is tested in `test/unit/tessel.js` needs the `controller.menu.create` to response with a single tessel.
For that reason I added **conditional code within the CLI** like that:
```
// within controller.menu.create
      if (!global.IS_TEST_ENV) {
        controller.menu.make(tessels, rtm, title)
          .then(controller.menu.show(rtm))
          .then(function(index) {
            resolve(tessels[index]);
          });
      } else {
        resolve(tessels[0]); // due to old tests what expect a single tessel returned by Tessel.get
      }
```
It isn't possible to come over that need because `controller.menu.create` is used in `Tessel.get`.
There would be a simple `cleaner` workaround:
```
// at the bottom of controller.js
if (global.IS_TEST_ENV) {
controller.menu = {
  create = function(tessels) {
     return new Promise(function(resolve) {
        resolve(tessels[0]);
     }
  });
}
```

}
```

**Comment by Student007** [comment]
> After you merge @johnnyman727's PR, please also merge this: Student007#3

@rwaldron :raised_hands: magic ... :+1: understand. Will roll back my local changes.

**Comment by rwaldron** [comment]
I know you put effort into writing tests and I appreciate that, but for now I'd rather we avoid conditional code paths. I'm working on writing you a "mock Menu" class, that's derived from `Menu`. We can land it in a follow up.

**Comment by Student007** [comment]
@rwaldron :+1:

**Comment by johnnyman727** [comment]
Looks good everyone! Will merge it now.

**Pull request merged**
