### PR TITLE
provision: correct permissions of ~/.tessel/id_rsa. Fixes gh-193

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by rwaldron** [comment]
These travis failures are garbage.

**Comment by johnnyman727** [comment]
Ah I used to have the permissions in this logic but must have accidentally taken them out when I refactored. Hooray for stellar unit tests!

I'm not sure what's up with Travis - on another PR it was failing to properly `npm install` a module.

**Comment by rwaldron** [comment]
> Hooray for stellar unit tests!

Well, now you'll sleep easier ;)

**Comment by rwaldron** [comment]
The failures only appear in pull requests

**Comment by rwaldron** [comment]
Confirmed: https://travis-ci.org/tessel/t2-cli/builds/70243983 this is a run from a branch, and it does not fail.

**Comment by johnnyman727** [comment]
Confirmed. Merging this now and we'll figure out what's going on with Travis afterward.

**Pull request merged**
