### PR TITLE
wifi ignores initial "command not found" error

### LINKED ISSUE #611: t2 wifi fails if not connected to wifi
I ran `t2 wifi` just to verify that my Tessel was not connected to wifi and I got this error:

```
➜  t2-cli git:(master) t2 wifi
INFO Looking for your Tessel...
INFO Connected to Tessel-02A30958C11A.
ERR! Error: Command failed: Not found
```

To reproduce, just disconnect your Tessel from wifi (`t2 wifi --off`) and then run `t2 wifi`.

### PR DESCRIPTION
**Pull request by HipsterBrown**
Fixes #611

### CODE REVIEW

**Comment by johnnyman727** [comment]
The implementation looks good and I ran through some smoke tests with positive results:
```
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Connected to "technicallyHome"
INFO IP Address: 192.168.8.115
INFO Signal Strength: (67/70)
INFO Bitrate: 41mbps
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi --off
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Wifi Disabled.
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi
INFO Looking for your Tessel...
INFO Connected to horse.
WARN horse is not connected to Wi-Fi (run "t2 wifi -l" to see available networks)
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi -n technicallyHome -p Rusty007
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Wifi Enabled.
INFO Wifi Connected. SSID: technicallyHome, password: Rusty007, security: psk2
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Connected to "technicallyHome"
INFO IP Address: 192.168.8.115
INFO Signal Strength: (67/70)
INFO Bitrate: 14mbps
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi --off
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Wifi Disabled.
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi
INFO Looking for your Tessel...
INFO Connected to horse.
WARN horse is not connected to Wi-Fi (run "t2 wifi -l" to see available networks)
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi --on
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Wifi Enabled.
➜  t2-cli git:(HipsterBrown-wifi-off-error) t2 wifi
INFO Looking for your Tessel...
INFO Connected to horse.
INFO Connected to "technicallyHome"
INFO IP Address: 192.168.8.115
INFO Signal Strength: (57/70)
INFO Bitrate: 15mbps
```

The only thing missing is an update to our unit test suite. I will add some and open a PR on your PR.

**Comment by johnnyman727** [comment]
@HipsterBrown https://github.com/HipsterBrown/t2-cli/pull/5.

**Comment by HipsterBrown** [comment]
@johnnyman727 Your tests have been added to this PR. Thanks for making them. :+1:

**Comment by johnnyman727** [comment]
Looks good!

**Pull request merged**
