### PR TITLE
fix issues with promise resolve in provisioning

### LINKED ISSUE #189: `t2 key generate` will overwrite existing SSH keys
The logic for checking if SSH keys already exists was moved out of the provisioning logic and into `controller.js` for the sake of speed.

Since `key generate` calls into the middle of the provisioning logic to just create a key (and not try to pass it to a Tessel 2), that check doesn't happen and new keys are made.

### PR DESCRIPTION
**Pull request by wprater**
fixes #189

### CODE REVIEW

**Comment by wprater** [comment]
this should fix #279 as well?

**Comment by johnnyman727** [comment]
@wprater this is great! I made a PR which should make our CI happy: https://github.com/wprater/t2-cli/pull/1

**Comment by johnnyman727** [comment]
Bonus points if you can squash these commits into one for cleanliness.

**Comment by wprater** [comment]
done!

**Comment by johnnyman727** [comment]
Perfect! Feel free to merge when you're ready. Thanks for the contribution!

**Pull request merged**
