### PR TITLE
Ensure that .tesselinclude and binary modules are ignored when using -s flag. Fixes gh-624

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by rwaldron** [comment]
@HipsterBrown review?

**Comment by HipsterBrown** [comment]
@rwaldron Checking it out now.

**Comment by HipsterBrown** [comment]
The code looks good to me. :+1:

## Smoke Test

1. Set up project
  ```
  mkdir tessel-test; cd tessel-test; 
  t2 init;
  npm install firmata;
  echo "package.json" > .tesselinclude
  touch index.js;
  ```

2. Paste this into index.js: 
  ```js
  var package = require("package.son");
  var Board = require("firmata");
  var board = new Board("/dev/ttyACM0");

  console.log(package.name);

  board.on("ready", function() {
    var pin = 13;
    var state = 1;

    board.pinMode(pin, board.MODES.OUTPUT);

    setInterval(function() {
      board.digitalWrite(pin, (state ^= 1));
    }, 500);
  });
  ```
3. Run `t2 run index.js -s`

===

## Result

```
Nicks-MacBook-Pro:tessel-test hipsterbrown$ t2 run index.js -s
INFO Looking for your Tessel...
INFO Connected to tessel-router.
INFO Building project.
INFO Writing project to RAM on tessel-router (2.048 kB)...
INFO Deployed.
INFO Running index.js...
module.js:339
    throw err;
    ^

Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/index.js:1:69)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

After editing `index.js` to require `package.json` after `firmata`, I saw the following results:

```
Nicks-MacBook-Pro:tessel-test hipsterbrown$ t2 run index.js -s
INFO Looking for your Tessel...
INFO Connected to tessel-router.
INFO Building project.
INFO Writing project to RAM on tessel-router (2.048 kB)...
INFO Deployed.
INFO Running index.js...
module.js:339
    throw err;
    ^

Error: Cannot find module 'firmata'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/index.js:1:69)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

Since neither `package.json` or `firmata` were included with the deployed code, a qualified success!! :+1:

**Comment by rwaldron** [comment]
Nice!! Thank you

**Pull request merged**
