### PR TITLE
Rename files with underscores to files with dashes. Fixes gh-656

### LINKED ISSUE #656: Rename files to use either dash or underscore, but not both
This is gross, let's fix it.

### PR DESCRIPTION
**Pull request by wyze**
Fixes #656

I opted not to change the `bash_completion` as it is not necessarily code related and has the potential to break user's existing tab completion.

### CODE REVIEW

**Comment by HipsterBrown** [comment]
# Smoke Test

**Setup:**
`mkdir tessel-test && cd tessel-test`
`t2 init`
`t2 run index.js`

**Results:**

```
Nicks-MacBook-Pro:tessel-test hipsterbrown$ t2 init
Initializing Tessel 2 Project...
Created package.json.
Created .tesselinclude.
Wrote "Hello World" to index.js
Nicks-MacBook-Pro:tessel-test hipsterbrown$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to tessel-router.
INFO Building project.
INFO Writing project to RAM on tessel-router (3.072 kB)...
INFO Deployed.
INFO Running index.js...
I'm blinking! (Press CTRL + C to stop)
```

LGTM :+1:

**Comment by rwaldron** [comment]
I really need to get better at this... If you haven't done so yet, please sign the CLA: http://dojofoundation.org/about/claForm

**Comment by wyze** [comment]
I have signed that before, I think for lodash. :) .. I tried to sign it again, just to make sure, and it told me my username/email is already on file.

You know, I have seen this automated before, where it checks to see if the user signed CLA or not when they submit a PR. I wouldn't mind trying to dig in how to automate it for the Tessel organization.

**Comment by rwaldron** [comment]
Oh, great! Perfect :)

**Pull request merged**
