### PR TITLE
Use the sha when there is no "official" build version available.

### PR DESCRIPTION
**Pull request by rwaldron**
This patch is best illustrated by the following screenshot: 

Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by tessel-highfive** [comment]
r? @tcr

(tessel-highfive has picked a reviewer for you, use r? to override)

**Comment by rwaldron** [comment]
r?

**Comment by rwaldron** [comment]
Whoops.

**Comment by rwaldron** [comment]
One day this CI will finish

**Pull request merged**
