### PR TITLE
lib: use setTimeout instead of setInterval

### PR DESCRIPTION
**Pull request by LinusU**
@johnnyman727 I'm very positive that you meant setTimeout here?

### CODE REVIEW

**Comment by johnnyman727** [comment]
Yes, you're correct! I have this fixed in my working copy of #182 but it would be better to get it in sooner. 

Thanks! Feel free to merge once TravisCI gives the :+1:.

**Comment by LinusU** [comment]
@johnnyman727 Travis says :-1: 

> Error: Could not initialize libusb. Check that your system has a usb controller.

I'm not sure what to do here?

**Comment by rwaldron** [comment]
We have a failing master at the moment. Please hold!

**Comment by rwaldron** [comment]
This failure doesn't make much sense and is definitely not related to the patch. I'm going to land this as is

**Comment by rwaldron** [comment]
```
$ grunt
Running "jshint:all" (jshint) task
>> 29 files lint free.

Running "jscs:all" (jscs) task
>> 29 files without code style errors.

Running "jsbeautifier:all" (jsbeautifier) task
Beautified 29 files, changed 0 files...OK

Running "nodeunit:tests" (nodeunit) task
Testing bin-tessel-2.js.......OK
Testing deploy.js...OK
Testing erase.js..OK
Testing discover.js.......OK
Testing name.js........OK
Testing provision.js...........OK
Testing tessel.js..OK
Testing wifi.js......OK
>> 119 assertions passed (2033ms)

Done, without errors.
```

**Comment by rwaldron** [comment]
https://github.com/tessel/t2-cli/commit/efe615f4819bd3efa83cd0816fc4819d72c1d9cb

**Pull request closed without merging**
