### PR TITLE
Fix call to undefined logging function in usb_connection.

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by johnnyman727** [comment]
Gah Travis is killing us! This builds fine on my machine.

**Comment by johnnyman727** [comment]
I restarted Travis after tinkering with some config stuff and now this PR test fails with the same issue as #209:
```
Running "jshint:all" (jshint) task
>> 32 files lint free.
Running "jscs:all" (jscs) task
>> 32 files without code style errors.
Running "jsbeautifier:all" (jsbeautifier) task
Beautified 32 files, changed 0 files...OK
Running "nodeunit:tests" (nodeunit) task
WARNING: No usb controller found on this system.
Testing bin-tessel-2.js.......OK
Testing deploy.js...OK
Testing erase.js..OK
Testing discover.js.......OK
Testing lan_connection.js......Fatal error: ENOENT, no such file or directory '/home/travis/.tessel/id_rsa'
The command "grunt" exited with 91.

```

**Comment by johnnyman727** [comment]
@rwaldron could you rebase on master? I think I fixed at least one of the Travis issues.

**Comment by rwaldron** [comment]
Interesting, this was passing yesterday.

**Comment by rwaldron** [comment]
Rebased, waiting on travis

**Comment by rwaldron** [comment]
Ok, rebased again with master, awaiting travis

**Comment by johnnyman727** [comment]
:clap: :clap:

**Pull request merged**
