### PR TITLE
mock build list requests to avoid potential s3 issues

### LINKED ISSUE #753: Unit Test fails if S3 is inaccessible
The `requestBuildList` function is not currently mocked so it will actually try to fetch builds from S3 when `nodeunit` is run. This will fail if the host does not have a wifi connection or if S3 has other issues (like SSL certs, etc.). We should mock `requestBuildList` in any nodeunit functions.

### PR DESCRIPTION
**Pull request by johnnyman727**
Fixes #753.

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@johnnyman727 Does appveyor need to be re-run? https://ci.appveyor.com/project/rwaldron/t2-cli/build/958

**Comment by johnnyman727** [comment]
@HipsterBrown perhaps. Sent up a new commit sha so it should restart (I don't know of any other way to do it).

**Comment by johnnyman727** [comment]
@HipsterBrown I'm not sure what's up with AppVeyer. It's failing with `Failed to provision build worker virtual machine in a cloud. Please try restarting build later.` Maybe someone with more AppVeyer experience can comment?

**Comment by HipsterBrown** [comment]
@johnnyman727 Yea I noticed that. I've been looking for a way to re-run the build without pushing new commits (like Travis allows) but I can't find anything in the docs. Looking through the support forums as well.

**Comment by HipsterBrown** [comment]
@johnnyman727 Looks to be an issue for other appveyor users today -> http://help.appveyor.com/discussions/problems/4750-failed-to-provision-build-worker-virtual-machine-in-a-cloud-please-try-restarting-build-later

**Comment by HipsterBrown** [comment]
LGTM once Appveyor passes. *fingers-crossed* && *knocks on wood*

**Pull request merged**
