### PR TITLE
Add command for retrieving local IP of tessel

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by rwaldron** [comment]
I need to land the appveyor branch, then you'll want to rebase

**Comment by rwaldron** [comment]
Can you add some tests for this? Let me know if you need help getting started

**Comment by johnnyman727** [comment]
@geek thanks for your contribution! Did you know that you can get your IP address with the `t2 wifi` command? Do you feel like you need a more explicit command?

**Comment by rwaldron** [comment]
> Did you know that you can get your IP address with the t2 wifi command?

I completely forgot

**Comment by geek** [comment]
@johnnyman727 ya, I noticed that command as well.  I will leave it up to you if you want a more direct command or not.

**Comment by rwaldron** [comment]
Since this is already available and a separate command is not in the milestones, lets punt on this for now. We can reopen and revisit at a later time.

**Pull request closed without merging**
